sonar.projectKey=toy-shop
sonar.projectName=toy-shop
sonar.sources=src
sonar.exclusions=**/node_modules/**,dist/**,coverage/**,**/src/tests/**
sonar.tests=src/tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://3.138.142.230:9000
